version: "3.8"

services:
  backand:
    build:
      context: ./backand
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
    pgdata:
        driver: local
        name: pgdata

networks:
  default:
    name: api-prod
    external: true